name: scalytics_app
description: AI-Based Scalp Care Optimization System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  image_picker: ^1.0.7
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  lottie: ^3.1.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  camera: ^0.10.5+9
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.5.6

  image: ^4.1.3  # 🔥 TAMBAH INI
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/